title: "My Jekyll Site"
description: "Just a live chat site"
theme: "jekyll-theme-primer" # You can change this to your chosen theme

exclude:
  - node_modules
  - vendor
  - README.md

markdown: kramdown
